/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#c55002",
        "on-primary": "#ffffff",
        "surface-tint": "#a14000",
        "surface-container-highest": "#ebe1da",
        "surface-container-high": "#f1e6df",
        "on-primary-container": "#fffbff",
        "tertiary-fixed": "#e6e2d8",
        "on-error-container": "#93000a",
        "background": "#fff8f4",
        "secondary-fixed-dim": "#b0cdbb",
        "tertiary-container": "#76756d",
        "primary-fixed": "#ffdbcc",
        "secondary-container": "#ccead6",
        "on-primary-fixed-variant": "#7b2f00",
        "on-secondary-container": "#4f6a5b",
        "inverse-primary": "#ffb694",
        "outline-variant": "#dfc0b3",
        "inverse-surface": "#352f2b",
        "on-primary-fixed": "#351000",
        "surface-dim": "#e2d8d1",
        "primary": "#9d3e00",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "surface": "#fff8f4",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#324c3e",
        "on-secondary-fixed": "#062014",
        "on-tertiary-fixed-variant": "#484740",
        "tertiary": "#5e5c55",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb694",
        "error-container": "#ffdad6",
        "on-surface-variant": "#584238",
        "on-tertiary-fixed": "#1c1c16",
        "outline": "#8c7166",
        "surface-bright": "#fff8f4",
        "on-background": "#1f1b17",
        "surface-container-low": "#fcf2ea",
        "tertiary-fixed-dim": "#cac6bd",
        "on-secondary": "#ffffff",
        "on-surface": "#1f1b17",
        "inverse-on-surface": "#f9efe8",
        "secondary-fixed": "#ccead6",
        "surface-variant": "#ebe1da",
        "secondary": "#496455",
        "surface-container": "#f6ece5",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "unit": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "headline-md": ["Literata"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Literata"],
        "label-sm": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Literata"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg": ["Literata"],
        "body-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
        "display-lg-mobile": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}